import { StyleSheet } from "react-native";

export const desktopProcessStyles = StyleSheet.create({
  desktopHeaderAction: { minWidth: 196 },
  desktopHeaderActions: { alignItems: "center", flexDirection: "row", gap: 10 },
  desktopDetailLayout: { flexDirection: "row", gap: 18, paddingBottom: 34 },
  desktopMainColumn: { flex: 1, gap: 16, minWidth: 0 },
  desktopSideColumn: { gap: 14, width: 326 },
  desktopDocumentCard: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 16, borderWidth: 1, gap: 16, padding: 19 },
  desktopDocumentTop: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  desktopDocumentIdentity: { alignItems: "center", flexDirection: "row", gap: 12 },
  desktopDocumentIcon: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 13, height: 44, justifyContent: "center", width: 44 },
  desktopDocumentLabel: { color: "#B7791F", fontSize: 10, fontWeight: "900", letterSpacing: 1 },
  desktopDocumentTitle: { color: "#17212B", fontSize: 18, fontWeight: "800", marginTop: 3 },
  desktopDocumentMeta: { color: "#607385", fontSize: 12, marginTop: 3 },
  desktopProgressRow: { alignItems: "flex-end", flexDirection: "row", justifyContent: "space-between" },
  desktopProgressText: { gap: 3 },
  desktopProgressTitle: { color: "#17212B", fontSize: 14, fontWeight: "800" },
  desktopProgressSubtitle: { color: "#607385", fontSize: 12 },
  desktopProgressValue: { color: "#103A5B", fontSize: 23, fontWeight: "800" },
  desktopProgressTrack: { backgroundColor: "#E5EBF0", borderRadius: 8, height: 8, overflow: "hidden" },
  desktopProgressFill: { backgroundColor: "#B48A2C", borderRadius: 8, height: 8 },
  desktopSequenceSection: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 16, borderWidth: 1, gap: 15, padding: 18 },
  desktopSequenceHead: { alignItems: "flex-end", flexDirection: "row", justifyContent: "space-between" },
  desktopSectionHeading: { color: "#17212B", fontSize: 16, fontWeight: "800" },
  desktopSectionCopy: { color: "#607385", fontSize: 12, marginTop: 4 },
  desktopSequenceLegend: { color: "#718397", fontSize: 11, fontWeight: "700" },
  desktopStageList: { gap: 9, paddingRight: 4 },
  desktopStageCard: { backgroundColor: "#F8FAFC", borderColor: "#D9E1E8", borderRadius: 13, borderWidth: 1, gap: 8, minHeight: 128, padding: 12, width: 166 },
  desktopStageCardSelected: { backgroundColor: "#FFFFFF", borderColor: "#103A5B", borderWidth: 2 },
  desktopStageCardHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  desktopStageNumber: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 11, height: 24, justifyContent: "center", width: 24 },
  desktopStageNumberText: { color: "#103A5B", fontSize: 11, fontWeight: "900" },
  desktopStageCardTitle: { color: "#17212B", flex: 1, fontSize: 13, fontWeight: "800", lineHeight: 18 },
  desktopStageCardSigner: { color: "#607385", fontSize: 11 },
  desktopSidebarCard: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 16, borderWidth: 1, gap: 12, padding: 16 },
  desktopSideTitleRow: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  desktopSideTitle: { color: "#17212B", fontSize: 15, fontWeight: "800" },
  desktopSideSubtitle: { color: "#718397", fontSize: 11, marginTop: 3 },
  desktopParticipant: { alignItems: "center", borderTopColor: "#EDF1F5", borderTopWidth: 1, flexDirection: "row", gap: 9, minHeight: 52, paddingVertical: 8 },
  desktopParticipantIndex: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 10, height: 21, justifyContent: "center", width: 21 },
  desktopParticipantIndexDone: { backgroundColor: "#DFF3E8" },
  desktopParticipantIndexText: { color: "#607385", fontSize: 10, fontWeight: "900" },
  desktopParticipantIndexTextDone: { color: "#1C7C54" },
  desktopParticipantInfo: { flex: 1, gap: 2 },
  desktopParticipantRole: { color: "#43576A", fontSize: 12, fontWeight: "800" },
  desktopParticipantName: { color: "#718397", fontSize: 11 },
  desktopTimelineItem: { alignItems: "flex-start", borderTopColor: "#EDF1F5", borderTopWidth: 1, flexDirection: "row", gap: 9, paddingVertical: 10 },
  desktopTimelineCopy: { flex: 1, gap: 3 },
  desktopTimelineDescription: { color: "#43576A", fontSize: 12, lineHeight: 17 },
  desktopTimelineMeta: { color: "#718397", fontSize: 10 },
  desktopAuditLink: { color: "#103A5B", fontSize: 11, fontWeight: "800", marginTop: 2 },
});
