import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";

import { DesktopShell, isDesktopLayout } from "@/components/desktop-shell";
import { ScreenContainer } from "@/components/screen-container";
import { OutlineButton, PrimaryButton } from "@/components/workflow-ui";
import { useWorkflow } from "@/lib/workflow-store";

type WorkflowForm = { protocol: string; candidateName: string; candidateRank: string; grade: string; opm: string };

export default function NewWorkflowScreen() {
  const router = useRouter();
  const { width } = useWindowDimensions();
  const { createWorkflow } = useWorkflow();
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState<WorkflowForm>({ protocol: "", candidateName: "", candidateRank: "", grade: "", opm: "" });
  const isDesktop = Platform.OS === "web" && isDesktopLayout(width);
  const valid = Object.values(form).every((value) => value.trim().length > 0);
  const set = (key: keyof WorkflowForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { if (!valid) { Alert.alert("Revise os dados", "Preencha todos os campos para criar a nova LMP."); return; } setSaving(true); try { const id = await createWorkflow(form); router.replace(`/processo/${id}` as any); } finally { setSaving(false); } };
  if (isDesktop) return <DesktopNewWorkflow form={form} set={set} submit={submit} saving={saving} onCancel={() => router.back()} />;
  return <MobileNewWorkflow form={form} set={set} submit={submit} saving={saving} />;
}

function DesktopNewWorkflow({ form, set, submit, saving, onCancel }: { form: WorkflowForm; set: (key: keyof WorkflowForm, value: string) => void; submit: () => Promise<void>; saving: boolean; onCancel: () => void }) {
  return <DesktopShell active="processos" title="Nova LMP" subtitle="Cadastre o indicado e libere a primeira etapa de preenchimento." action={<View style={styles.desktopAction}><OutlineButton label="Cancelar" icon="close" onPress={onCancel} /></View>}><View style={styles.desktopGrid}><View style={styles.desktopFormPanel}><View style={styles.desktopFormHead}><View style={styles.desktopFormIcon}><MaterialIcons name="description" size={24} color="#103A5B" /></View><View><Text style={styles.desktopKicker}>PM-COM-002</Text><Text style={styles.desktopFormTitle}>Dados iniciais da indicação</Text><Text style={styles.desktopFormSubtitle}>Estes dados compõem a abertura do processo e ficam visíveis aos participantes autorizados.</Text></View></View><View style={styles.desktopFormFields}><Field label="Protocolo / nº SEI/SP" value={form.protocol} onChangeText={(value) => set("protocol", value)} placeholder="Ex.: SEI/SP 042/2026" /><Field label="Posto / graduação" value={form.candidateRank} onChangeText={(value) => set("candidateRank", value)} placeholder="Ex.: Soldado PM" /><Field label="Nome completo" value={form.candidateName} onChangeText={(value) => set("candidateName", value)} placeholder="Nome do militar indicado" /><View style={styles.desktopFieldRow}><View style={styles.desktopFieldHalf}><Field label="OPM" value={form.opm} onChangeText={(value) => set("opm", value)} placeholder="Ex.: 7º BPM/M" /></View><View style={styles.desktopFieldHalf}><Field label="Grau da LMP" value={form.grade} onChangeText={(value) => set("grade", value)} placeholder="Ex.: 3º grau" /></View></View></View><View style={styles.desktopFormFooter}><Text style={styles.desktopFooterCopy}>Ao criar, a etapa de indicação será liberada e o fluxo ficará disponível na lista de processos.</Text><View style={styles.desktopCreateButton}><PrimaryButton label="Criar e liberar indicação" onPress={submit} loading={saving} icon="arrow-forward" /></View></View></View><View style={styles.desktopInfoColumn}><View style={styles.desktopInfoCard}><Text style={styles.desktopInfoTitle}>Sequência preparada</Text><Text style={styles.desktopInfoSubtitle}>O processo nasce com responsabilidades ordenadas.</Text><FlowItem index="1" title="Responsável pela indicação" copy="Registra a síntese histórica e confirma a indicação." active /><FlowItem index="2" title="Informações pessoais" copy="Oficial P/1 ou secretário valida os requisitos." /><FlowItem index="3" title="Informações disciplinares" copy="Oficial PJMD ou equivalente registra a análise." /><FlowItem index="4" title="Pareceres e concessão" copy="Autoridades responsáveis registram decisão e encerramento." /></View><View style={styles.desktopLockNote}><MaterialIcons name="lock" size={21} color="#607385" /><Text style={styles.desktopLockText}>Após cada confirmação, os campos da etapa assinada são bloqueados e preservados na trilha de auditoria.</Text></View></View></View></DesktopShell>;
}

function FlowItem({ index, title, copy, active }: { index: string; title: string; copy: string; active?: boolean }) { return <View style={styles.flowItem}><View style={[styles.flowIndex, active && styles.flowIndexActive]}><Text style={[styles.flowIndexText, active && styles.flowIndexTextActive]}>{index}</Text></View><View style={styles.flowCopy}><Text style={styles.flowTitle}>{title}</Text><Text style={styles.flowText}>{copy}</Text></View></View>; }

function MobileNewWorkflow({ form, set, submit, saving }: { form: WorkflowForm; set: (key: keyof WorkflowForm, value: string) => void; submit: () => Promise<void>; saving: boolean }) { return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.nav}><MaterialIcons name="description" size={26} color="#103A5B" /><Text style={styles.navText}>Nova LMP</Text></View><View><Text style={styles.eyebrow}>PM-COM-002</Text><Text style={styles.heading}>Inicie a tramitação</Text><Text style={styles.subtitle}>O primeiro bloco será liberado após a criação. A ordem dos demais responsáveis já estará preparada.</Text></View><View style={styles.formCard}><Field label="Protocolo / nº SEI/SP" value={form.protocol} onChangeText={(value) => set("protocol", value)} placeholder="Ex.: SEI/SP 042/2026" /><Field label="Posto / graduação" value={form.candidateRank} onChangeText={(value) => set("candidateRank", value)} placeholder="Ex.: Soldado PM" /><Field label="Nome completo" value={form.candidateName} onChangeText={(value) => set("candidateName", value)} placeholder="Nome do militar indicado" /><Field label="OPM" value={form.opm} onChangeText={(value) => set("opm", value)} placeholder="Ex.: 7º BPM/M" /><Field label="Grau da LMP" value={form.grade} onChangeText={(value) => set("grade", value)} placeholder="Ex.: 3º grau" /></View><View style={styles.notice}><MaterialIcons name="lock" size={19} color="#607385" /><Text style={styles.noticeText}>Os dados permanecerão editáveis até a assinatura da etapa correspondente. Depois disso, o bloco será bloqueado e preservado no histórico.</Text></View><PrimaryButton label="Criar e liberar indicação" onPress={submit} loading={saving} icon="arrow-forward" /></ScrollView></KeyboardAvoidingView></ScreenContainer>; }

function Field({ label, value, onChangeText, placeholder }: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#94A3B8" style={styles.input} returnKeyType="done" /></View>; }

const styles = StyleSheet.create({
  flex: { flex: 1 }, desktopAction: { minWidth: 120 }, desktopGrid: { alignItems: "flex-start", flexDirection: "row", gap: 18, paddingBottom: 34 }, desktopFormPanel: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 17, borderWidth: 1, flex: 1, gap: 22, padding: 22 }, desktopFormHead: { alignItems: "flex-start", flexDirection: "row", gap: 13 }, desktopFormIcon: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 13, height: 45, justifyContent: "center", width: 45 }, desktopKicker: { color: "#B7791F", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, desktopFormTitle: { color: "#17212B", fontSize: 19, fontWeight: "800", marginTop: 3 }, desktopFormSubtitle: { color: "#607385", fontSize: 12, lineHeight: 18, marginTop: 4, maxWidth: 500 }, desktopFormFields: { gap: 15 }, desktopFieldRow: { flexDirection: "row", gap: 15 }, desktopFieldHalf: { flex: 1 }, desktopFormFooter: { alignItems: "center", borderTopColor: "#E5EBF0", borderTopWidth: 1, flexDirection: "row", gap: 16, justifyContent: "space-between", paddingTop: 18 }, desktopFooterCopy: { color: "#607385", flex: 1, fontSize: 12, lineHeight: 18 }, desktopCreateButton: { minWidth: 252 }, desktopInfoColumn: { gap: 14, width: 336 }, desktopInfoCard: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 17, borderWidth: 1, gap: 13, padding: 18 }, desktopInfoTitle: { color: "#17212B", fontSize: 16, fontWeight: "800" }, desktopInfoSubtitle: { color: "#607385", fontSize: 12, lineHeight: 17, marginBottom: 3 }, flowItem: { alignItems: "flex-start", borderTopColor: "#EDF1F5", borderTopWidth: 1, flexDirection: "row", gap: 10, paddingTop: 12 }, flowIndex: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 11, height: 23, justifyContent: "center", width: 23 }, flowIndexActive: { backgroundColor: "#FFF3D7" }, flowIndexText: { color: "#607385", fontSize: 11, fontWeight: "900" }, flowIndexTextActive: { color: "#B7791F" }, flowCopy: { flex: 1, gap: 3 }, flowTitle: { color: "#43576A", fontSize: 12, fontWeight: "800" }, flowText: { color: "#718397", fontSize: 11, lineHeight: 16 }, desktopLockNote: { alignItems: "flex-start", backgroundColor: "#EEF3F7", borderRadius: 14, flexDirection: "row", gap: 10, padding: 14 }, desktopLockText: { color: "#536576", flex: 1, fontSize: 12, lineHeight: 18 },
  content: { gap: 20, paddingBottom: 24, paddingTop: 8 }, nav: { alignItems: "center", flexDirection: "row", gap: 9 }, navText: { color: "#103A5B", fontSize: 16, fontWeight: "800" }, eyebrow: { color: "#B48A2C", fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, heading: { color: "#17212B", fontSize: 28, fontWeight: "800", marginTop: 5 }, subtitle: { color: "#607385", fontSize: 15, lineHeight: 21, marginTop: 5 }, formCard: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 18, borderWidth: 1, gap: 15, padding: 16 }, field: { gap: 7 }, label: { color: "#43576A", fontSize: 13, fontWeight: "700" }, input: { backgroundColor: "#F8FAFC", borderColor: "#D9E1E8", borderRadius: 11, borderWidth: 1, color: "#17212B", fontSize: 16, minHeight: 48, paddingHorizontal: 13 }, notice: { alignItems: "flex-start", backgroundColor: "#EEF3F7", borderRadius: 14, flexDirection: "row", gap: 10, padding: 14 }, noticeText: { color: "#536576", flex: 1, fontSize: 13, lineHeight: 19 },
});
