import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ActivityIndicator, Alert, FlatList, Platform, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";

import { DesktopShell, isDesktopLayout } from "@/components/desktop-shell";
import { ScreenContainer } from "@/components/screen-container";
import { OutlineButton, StageStatusPill } from "@/components/workflow-ui";
import { useWorkflow } from "@/lib/workflow-store";

export default function AlertsScreen() {
  const { width } = useWindowDimensions();
  const isDesktop = Platform.OS === "web" && isDesktopLayout(width);
  const workflow = useWorkflow();
  if (!workflow.isReady) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color="#103A5B" size="large" /></ScreenContainer>;
  return isDesktop ? <DesktopAlerts /> : <MobileAlerts />;
}

function DesktopAlerts() {
  const router = useRouter();
  const { documents, sendReminder } = useWorkflow();
  const notices = documents.map((document) => ({ document, stage: document.stages.find((stage) => stage.status === "active") })).filter((item) => item.stage);
  return <DesktopShell active="avisos" title="Pendências e avisos" subtitle="Controle a fila de signatários e acompanhe os avisos vinculados a cada etapa." >
    <FlatList data={notices} keyExtractor={(item) => item.document.id} contentContainerStyle={styles.desktopContent} ListHeaderComponent={<View style={styles.desktopHeader}><View style={styles.desktopCount}><View style={styles.desktopBell}><MaterialIcons name="notifications-active" size={23} color="#B7791F" /></View><View><Text style={styles.desktopCountValue}>{notices.length} pendência{notices.length === 1 ? "" : "s"} ativa{notices.length === 1 ? "" : "s"}</Text><Text style={styles.desktopCountLabel}>O próximo responsável é avisado ao ser liberado no fluxo.</Text></View></View><View style={styles.desktopInfo}><MaterialIcons name="info-outline" size={18} color="#536576" /><Text style={styles.desktopInfoText}>O reenvio gera evidência na auditoria. A entrega remota será conectada ao canal institucional na implantação.</Text></View></View>} renderItem={({ item }) => item.stage ? <View style={styles.desktopRow}><View style={styles.desktopRowLead}><View style={styles.desktopBell}><MaterialIcons name="notifications-active" size={21} color="#B7791F" /></View><View style={styles.desktopRowLeadText}><Text style={styles.desktopStageTitle}>{item.stage.title}</Text><Text style={styles.desktopProtocol}>{item.document.protocol} · {item.document.candidateRank} {item.document.candidateName}</Text></View></View><View style={styles.desktopSigner}><Text style={styles.desktopColumnLabel}>RESPONSÁVEL</Text><Text style={styles.desktopSignerName}>{item.stage.signerName}</Text><Text style={styles.desktopSignerRole}>{item.stage.role}</Text></View><View style={styles.desktopStatus}><StageStatusPill status={item.stage.status} /></View><View style={styles.desktopActions}><OutlineButton label="Reenviar aviso" icon="notifications-none" onPress={async () => { await sendReminder(item.document.id); Alert.alert("Aviso preparado", `A pendência para ${item.stage?.signerName} foi registrada na linha do tempo.`); }} /><Pressable onPress={() => router.push(`/processo/${item.document.id}` as any)} style={({ pressed }) => [styles.desktopOpen, pressed && styles.pressed]}><Text style={styles.desktopOpenText}>Abrir</Text><MaterialIcons name="arrow-forward" size={18} color="#103A5B" /></Pressable></View></View> : null} ListEmptyComponent={<View style={styles.desktopEmpty}><MaterialIcons name="notifications-off" size={34} color="#607385" /><Text style={styles.desktopEmptyTitle}>Nenhuma pendência ativa.</Text><Text style={styles.desktopEmptyText}>Os próximos responsáveis aparecerão aqui automaticamente à medida que as etapas forem liberadas.</Text></View>} />
  </DesktopShell>;
}

function MobileAlerts() {
  const router = useRouter();
  const { documents, sendReminder } = useWorkflow();
  const notices = documents.map((document) => ({ document, stage: document.stages.find((stage) => stage.status === "active") })).filter((item) => item.stage);
  return <ScreenContainer className="px-5"><FlatList data={notices} keyExtractor={(item) => item.document.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>CENTRAL DE AVISOS</Text><Text style={styles.heading}>Pendências de assinatura</Text><Text style={styles.subtitle}>Cada aviso aponta a próxima etapa liberada. O envio externo será conectado ao canal institucional na implantação.</Text></View>} renderItem={({ item }) => item.stage ? <View style={styles.card}><View style={styles.cardTop}><View style={styles.bell}><MaterialIcons name="notifications-active" size={22} color="#B7791F" /></View><StageStatusPill status={item.stage.status} /></View><Text style={styles.title}>{item.stage.title}</Text><Text style={styles.body}>{item.stage.signerName} · {item.stage.role}</Text><Text style={styles.protocol}>{item.document.protocol} · {item.document.candidateName}</Text><View style={styles.actions}><OutlineButton label="Reenviar aviso" onPress={async () => { await sendReminder(item.document.id); Alert.alert("Aviso preparado", `A pendência para ${item.stage?.signerName} foi registrada na linha do tempo.`); }} /><Pressable onPress={() => router.push(`/processo/${item.document.id}` as any)}><Text style={styles.open}>Abrir processo</Text></Pressable></View></View> : null} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="notifications-off" size={30} color="#607385" /><Text style={styles.emptyTitle}>Sem avisos pendentes</Text><Text style={styles.emptyText}>Quando uma etapa for liberada, o próximo responsável aparecerá nesta central.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  desktopContent: { gap: 14, paddingBottom: 32 }, desktopHeader: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 16, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginBottom: 8, padding: 19 }, desktopCount: { alignItems: "center", flexDirection: "row", gap: 12 }, desktopBell: { alignItems: "center", backgroundColor: "#FFF3D7", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, desktopCountValue: { color: "#17212B", fontSize: 18, fontWeight: "800" }, desktopCountLabel: { color: "#607385", fontSize: 12, marginTop: 4 }, desktopInfo: { alignItems: "flex-start", backgroundColor: "#EEF3F7", borderRadius: 12, flexDirection: "row", gap: 8, maxWidth: 410, padding: 11 }, desktopInfoText: { color: "#536576", flex: 1, fontSize: 11, lineHeight: 16 }, desktopRow: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 15, borderWidth: 1, flexDirection: "row", minHeight: 96, padding: 16 }, desktopRowLead: { alignItems: "center", flex: 1.3, flexDirection: "row", gap: 11, minWidth: 0 }, desktopRowLeadText: { flex: 1, gap: 4 }, desktopStageTitle: { color: "#17212B", fontSize: 15, fontWeight: "800" }, desktopProtocol: { color: "#607385", fontSize: 11, lineHeight: 16 }, desktopSigner: { borderLeftColor: "#E5EBF0", borderLeftWidth: 1, flex: 1, gap: 3, minWidth: 0, paddingLeft: 22 }, desktopColumnLabel: { color: "#718397", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, desktopSignerName: { color: "#17212B", fontSize: 13, fontWeight: "800" }, desktopSignerRole: { color: "#607385", fontSize: 11 }, desktopStatus: { flex: 0.6 }, desktopActions: { alignItems: "center", flexDirection: "row", gap: 12, justifyContent: "flex-end", minWidth: 246 }, desktopOpen: { alignItems: "center", flexDirection: "row", gap: 4, padding: 8 }, desktopOpenText: { color: "#103A5B", fontSize: 13, fontWeight: "800" }, desktopEmpty: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 16, borderWidth: 1, gap: 8, padding: 32 }, desktopEmptyTitle: { color: "#17212B", fontSize: 16, fontWeight: "800" }, desktopEmptyText: { color: "#607385", fontSize: 13, maxWidth: 420, textAlign: "center" },
  content: { gap: 14, paddingBottom: 28, paddingTop: 10 }, header: { gap: 5, marginBottom: 4 }, eyebrow: { color: "#B48A2C", fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, heading: { color: "#17212B", fontSize: 28, fontWeight: "800" }, subtitle: { color: "#607385", fontSize: 14, lineHeight: 20 }, card: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 18, borderWidth: 1, gap: 9, padding: 16 }, cardTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, bell: { alignItems: "center", backgroundColor: "#FFF3D7", borderRadius: 13, height: 40, justifyContent: "center", width: 40 }, title: { color: "#17212B", fontSize: 18, fontWeight: "800" }, body: { color: "#43576A", fontSize: 14 }, protocol: { color: "#718397", fontSize: 12 }, actions: { gap: 12, marginTop: 5 }, open: { color: "#103A5B", fontSize: 14, fontWeight: "800", textAlign: "center" }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 18, borderWidth: 1, gap: 8, padding: 28 }, emptyTitle: { color: "#17212B", fontSize: 17, fontWeight: "800" }, emptyText: { color: "#607385", fontSize: 14, lineHeight: 20, textAlign: "center" }, pressed: { opacity: 0.7 },
});
