import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ActivityIndicator, FlatList, Platform, Pressable, StyleSheet, Text, useWindowDimensions, View } from "react-native";

import { DesktopShell, isDesktopLayout } from "@/components/desktop-shell";
import { ScreenContainer } from "@/components/screen-container";
import { PrimaryButton, StageStatusPill } from "@/components/workflow-ui";
import { useWorkflow } from "@/lib/workflow-store";

export default function ProcessesScreen() {
  const { width } = useWindowDimensions();
  const isDesktop = Platform.OS === "web" && isDesktopLayout(width);
  const workflow = useWorkflow();
  if (!workflow.isReady) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color="#103A5B" size="large" /></ScreenContainer>;
  return isDesktop ? <DesktopProcesses /> : <MobileProcesses />;
}

function DesktopProcesses() {
  const router = useRouter();
  const { documents } = useWorkflow();
  const inProgress = documents.filter((document) => document.status === "in_progress").length;
  const completed = documents.filter((document) => document.status === "completed").length;
  return <DesktopShell active="processos" title="Processos LMP" subtitle="Consulte o trâmite completo e abra a etapa autorizada para cada indicação." action={<View style={styles.action}><PrimaryButton label="Nova LMP" icon="add-circle-outline" onPress={() => router.push("/processo/novo" as any)} /></View>}>
    <FlatList data={documents} keyExtractor={(document) => document.id} contentContainerStyle={styles.desktopContent} ListHeaderComponent={<><View style={styles.summaryRow}><Summary label="Em tramitação" value={String(inProgress)} icon="pending-actions" tone="gold" /><Summary label="Concluídos" value={String(completed)} icon="verified" tone="green" /><Summary label="Modelo ativo" value="PM-COM-002" icon="description" tone="blue" /></View><View style={styles.tableHead}><Text style={[styles.tableHeadLabel, styles.colCandidate]}>Indicado e protocolo</Text><Text style={[styles.tableHeadLabel, styles.colStage]}>Etapa atual</Text><Text style={[styles.tableHeadLabel, styles.colProgress]}>Progresso</Text><Text style={[styles.tableHeadLabel, styles.colStatus]}>Situação</Text><View style={styles.colAction} /></View></>} renderItem={({ item }) => {
      const active = item.stages.find((stage) => stage.status === "active");
      const finished = item.stages.filter((stage) => stage.status === "signed" || stage.status === "skipped").length;
      const percentage = Math.round((finished / item.stages.length) * 100);
      return <Pressable onPress={() => router.push(`/processo/${item.id}` as any)} style={({ pressed }) => [styles.tableRow, pressed && styles.pressed]}><View style={styles.colCandidate}><View style={styles.rowCandidate}><View style={styles.rowIcon}><MaterialIcons name="description" size={20} color="#103A5B" /></View><View style={styles.rowCandidateText}><Text style={styles.candidateName}>{item.candidateRank} {item.candidateName}</Text><Text style={styles.protocol}>{item.protocol} · {item.opm} · {item.grade}</Text></View></View></View><View style={styles.colStage}>{active ? <><Text style={styles.stageName}>{active.title}</Text><Text style={styles.stageSigner}>{active.signerName}</Text></> : <Text style={styles.stageName}>Fluxo concluído</Text>}</View><View style={styles.colProgress}><View style={styles.progressLine}><View style={[styles.progressFill, { width: `${percentage}%` }]} /></View><Text style={styles.progressText}>{finished}/{item.stages.length} etapas · {percentage}%</Text></View><View style={styles.colStatus}>{active ? <StageStatusPill status={active.status} /> : <Text style={styles.completeText}>Concluído</Text>}</View><View style={styles.colAction}><MaterialIcons name="arrow-forward" size={20} color="#103A5B" /></View></Pressable>;
    }} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="folder-open" size={34} color="#607385" /><Text style={styles.emptyTitle}>Ainda não há processos cadastrados.</Text><Text style={styles.emptyText}>Crie uma LMP para iniciar a tramitação digital.</Text></View>} />
  </DesktopShell>;
}

function Summary({ label, value, icon, tone }: { label: string; value: string; icon: keyof typeof MaterialIcons.glyphMap; tone: "gold" | "green" | "blue" }) {
  const colors = { gold: ["#FFF3D7", "#B7791F"], green: ["#E7F5EC", "#1C7C54"], blue: ["#E7F0F7", "#103A5B"] } as const;
  return <View style={styles.summaryCard}><View style={[styles.summaryIcon, { backgroundColor: colors[tone][0] }]}><MaterialIcons name={icon} size={20} color={colors[tone][1]} /></View><View><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View></View>;
}

function MobileProcesses() {
  const router = useRouter();
  const { documents } = useWorkflow();
  return <ScreenContainer className="px-5"><FlatList data={documents} keyExtractor={(document) => document.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><View><Text style={styles.eyebrow}>PM-COM-002</Text><Text style={styles.heading}>Processos LMP</Text><Text style={styles.subtitle}>Todos os participantes visualizam a mesma sequência e histórico.</Text></View><PrimaryButton label="Nova LMP" icon="add-circle-outline" onPress={() => router.push("/processo/novo" as any)} /></View>} renderItem={({ item }) => { const active = item.stages.find((stage) => stage.status === "active"); const completed = item.stages.filter((stage) => stage.status === "signed" || stage.status === "skipped").length; return <Pressable onPress={() => router.push(`/processo/${item.id}` as any)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardHeader}><View style={styles.documentIcon}><MaterialIcons name="description" size={23} color="#103A5B" /></View><Text style={[styles.status, item.status === "completed" ? styles.complete : styles.progress]}>{item.status === "completed" ? "Concluído" : "Em tramitação"}</Text></View><Text style={styles.mobileCandidate}>{item.candidateRank} {item.candidateName}</Text><Text style={styles.meta}>{item.protocol} · {item.opm} · {item.grade}</Text><View style={styles.mobileProgressTrack}><View style={[styles.mobileProgressFill, { width: `${Math.round((completed / item.stages.length) * 100)}%` }]} /></View><View style={styles.cardFooter}><Text style={styles.footerText}>{completed} de {item.stages.length} etapas concluídas</Text>{active ? <StageStatusPill status={active.status} /> : <MaterialIcons name="verified" color="#1C7C54" size={19} />}</View></Pressable>; }} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="folder-open" size={32} color="#607385" /><Text style={styles.emptyText}>Crie uma LMP para iniciar o trâmite.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  action: { minWidth: 166 }, desktopContent: { gap: 0, paddingBottom: 32 }, summaryRow: { flexDirection: "row", gap: 14, marginBottom: 24 }, summaryCard: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 15, borderWidth: 1, flex: 1, flexDirection: "row", gap: 10, padding: 14 }, summaryIcon: { alignItems: "center", borderRadius: 11, height: 38, justifyContent: "center", width: 38 }, summaryValue: { color: "#17212B", fontSize: 20, fontWeight: "800" }, summaryLabel: { color: "#607385", fontSize: 12, marginTop: 2 }, tableHead: { alignItems: "center", backgroundColor: "#EAF0F5", borderBottomColor: "#D9E1E8", borderTopLeftRadius: 14, borderTopRightRadius: 14, borderWidth: 1, flexDirection: "row", minHeight: 47, paddingHorizontal: 17 }, tableHeadLabel: { color: "#536576", fontSize: 11, fontWeight: "900", letterSpacing: 0.4, textTransform: "uppercase" }, colCandidate: { flex: 1.5, minWidth: 0 }, colStage: { flex: 1.1, minWidth: 0 }, colProgress: { flex: 1, minWidth: 0 }, colStatus: { alignItems: "flex-start", flex: 0.7 }, colAction: { alignItems: "flex-end", width: 42 }, tableRow: { alignItems: "center", backgroundColor: "#FFFFFF", borderBottomColor: "#E3EAF0", borderBottomWidth: 1, borderLeftColor: "#D9E1E8", borderLeftWidth: 1, borderRightColor: "#D9E1E8", borderRightWidth: 1, flexDirection: "row", minHeight: 91, paddingHorizontal: 17 }, rowCandidate: { alignItems: "center", flexDirection: "row", gap: 10 }, rowIcon: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 11, height: 37, justifyContent: "center", width: 37 }, rowCandidateText: { flex: 1, gap: 3 }, candidateName: { color: "#17212B", fontSize: 14, fontWeight: "800" }, protocol: { color: "#607385", fontSize: 11, lineHeight: 16 }, stageName: { color: "#17212B", fontSize: 13, fontWeight: "800" }, stageSigner: { color: "#607385", fontSize: 11, marginTop: 4 }, progressLine: { backgroundColor: "#E5EBF0", borderRadius: 8, height: 7, overflow: "hidden", width: "86%" }, progressFill: { backgroundColor: "#B48A2C", borderRadius: 8, height: 7 }, progressText: { color: "#718397", fontSize: 11, marginTop: 6 }, completeText: { color: "#1C7C54", fontSize: 12, fontWeight: "800" }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 18, borderWidth: 1, gap: 10, padding: 28 }, emptyTitle: { color: "#17212B", fontSize: 16, fontWeight: "800" }, emptyText: { color: "#607385", fontSize: 14, textAlign: "center" }, pressed: { opacity: 0.72 },
  content: { gap: 13, paddingBottom: 28, paddingTop: 10 }, header: { gap: 14, paddingBottom: 10 }, eyebrow: { color: "#B48A2C", fontSize: 12, fontWeight: "800", letterSpacing: 1.2 }, heading: { color: "#17212B", fontSize: 28, fontWeight: "800", marginTop: 4 }, subtitle: { color: "#607385", fontSize: 14, lineHeight: 20, marginTop: 4 }, card: { backgroundColor: "#FFFFFF", borderColor: "#D9E1E8", borderRadius: 18, borderWidth: 1, gap: 9, padding: 16 }, cardHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, documentIcon: { alignItems: "center", backgroundColor: "#EAF0F5", borderRadius: 13, height: 40, justifyContent: "center", width: 40 }, status: { borderRadius: 999, fontSize: 12, fontWeight: "800", paddingHorizontal: 9, paddingVertical: 5 }, progress: { backgroundColor: "#FFF3D7", color: "#976C18" }, complete: { backgroundColor: "#DFF3E8", color: "#1C7C54" }, mobileCandidate: { color: "#17212B", fontSize: 18, fontWeight: "800" }, meta: { color: "#607385", fontSize: 13 }, mobileProgressTrack: { backgroundColor: "#E8EDF2", borderRadius: 8, height: 7, overflow: "hidden" }, mobileProgressFill: { backgroundColor: "#B48A2C", borderRadius: 8, height: 7 }, cardFooter: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, footerText: { color: "#718397", fontSize: 12, fontWeight: "600" },
});
